### ISSUE TITLE
Deploy problems

### ISSUE THREAD

**Issue by blacRose** [chimera/chimeraarts.org#1]
If I try to use the deploy script, it throws an error, saying 

	~/github/chimeraarts $ ./deploy.sh 'fixing a typo'
	Deploying updates to Github...
	16 pages created
	0 tags index created
	0 categories index created
	in 30 ms
	On branch master
	Your branch is up-to-date with 'origin/master'.

	nothing to commit, working directory clean
	Username for 'https://github.com': blacRose
	Password for 'https://blacRose@github.com':
	Everything up-to-date
	git push using:  public master
	-n 1/      58 (0)
	-n 2/      58 (1)
	-n 3/      58 (2)
	-n 4/      58 (3)
	-n 5/      58 (4)
	-n 6/      58 (5)
	-n 7/      58 (6)
	-n 8/      58 (7)
	-n 9/      58 (8)
	-n 10/      58 (8)
	-n 11/      58 (9)
	-n 12/      58 (10)
	-n 13/      58 (11)
	-n 14/      58 (12)
	-n 15/      58 (13)
	-n 16/      58 (14)
	-n 17/      58 (15)
	-n 18/      58 (16)
	-n 19/      58 (17)
	-n 20/      58 (18)
	-n 21/      58 (19)
	-n 22/      58 (20)
	-n 23/      58 (21)
	-n 24/      58 (22)
	-n 25/      58 (23)
	-n 26/      58 (24)
	-n 27/      58 (25)
	-n 28/      58 (26)
	-n 29/      58 (27)
	-n 30/      58 (28)
	-n 31/      58 (29)
	-n 32/      58 (30)
	-n 33/      58 (31)
	-n 34/      58 (32)
	-n 35/      58 (33)
	-n 36/      58 (34)
	-n 37/      58 (35)
	-n 38/      58 (36)
	-n 39/      58 (37)
	-n 40/      58 (38)
	-n 41/      58 (39)
	-n 42/      58 (40)
	-n 43/      58 (41)
	-n 44/      58 (42)
	-n 45/      58 (43)
	-n 46/      58 (44)
	-n 47/      58 (45)
	-n 48/      58 (46)
	-n 49/      58 (47)
	-n 50/      58 (48)
	-n 51/      58 (49)
	-n 52/      58 (50)
	-n 53/      58 (51)
	-n 54/      58 (52)
	-n 55/      58 (53)
	-n 56/      58 (54)
	-n 57/      58 (55)
	-n 58/      58 (56)
	fatal: 'public' does not appear to be a git repository
	fatal: Could not read from remote repository.

	Please make sure you have the correct access rights
	and the repository exists.

**Comment by danawoodman** [comment]
@blacRose see the above to make sure you've got your deploy setup properly. We're going to be rebuilding the website soon and moving all our info over to the Wiki: https://github.com/chimera/guidebook/wiki
