### ISSUE TITLE
Server needs to pull

### ISSUE THREAD

**Issue by blacRose** [chimera/chimeraarts.org#5]
Seems rather easy, I'm just at work and don't want to fork right now. I'll look at it after the event tonight if you don't fix it by then.

**Comment by blacRose** [comment]
Fixed, can you git pull on the server?

**Comment by danawoodman** [comment]
@blacRose I'm not sure what you're referring to by the server needs 'to pull'. Is something out of date that you see?

**Comment by danawoodman** [comment]
Oh, I see, you've committed something and it's not updating. Let me look into it. `publish` should do the trick...
